### ISSUE TITLE
Way to count # of NSFW images instead of hiding/showing them?

### ISSUE THREAD

**Issue by lusseyarmet** [nsfw-filter/nsfw-filter#102]
(Not really a feature request but closer than a bug) 

Is there a way to simply count the number of images the filter deems NSFW instead of hiding/showing them?

Right now to get the same result, I'm waiting for it to unhide all the SFW images and then count those but basically my goal would be to make the extension count them as soon as the page loads and not change visibility (as that takes the most time) but instead display the count in the page title. (so for example, "nsfw - Google Search" would become "nsfw - Google Search (10)" or something like that.

I'd greatly appreciate any pointers - if it's possible, what I'd need to edit or how. 

Thanks! :)

**Comment by navendu-pottekkat** [comment]
@lusseyarmet We are actually working on that feature right now. Check #79 

Please check the proposed design there and let us know how we can improve!

**Comment by lusseyarmet** [comment]
@navendu-pottekkat that sounds like a good feature! I'll try to think of some suggestions, this is a great extension. 
But as far as I know I wouldn't be able to access / retrieve the count itself if it was only in the badge, right? I'm using VBA and Selenium so my goal is to automate getting the count for a lot of pages to get some data for a chart, and I don't think VBA and Selenium can access the UI itself. Would a simple "return variable" in an executescript work? I saw in that post you linked that #78 mentions a variable (blockedItems) that sounds perfect but is it working right now? 

Thanks for the quick response!

**Comment by navendu-pottekkat** [comment]
@lusseyarmet The popup is not working right now but we have a variable that has this value that you can maybe access. @YegorZaremba Could you share that?

**Comment by YegorZaremba** [comment]
Hi @lusseyarmet 

> I saw in that post you linked that #78 mentions a variable (blockedItems) that sounds perfect but is it working right now?

Should works, pls fork repo and change [here](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L41) `this.blockedItems` to `window.blockedItems`. I guess after that you can access `window.blockedItems` in your `Selenium` environment

**Comment by lusseyarmet** [comment]
@YegorZaremba thanks, I replaced all occurences of `this.blockedItems` with `window.blockedItems` in content.js so that should work, right? I'm trying to execute the following script `return window.blockedItems` in VBA / Selenium but it's returning a blank string (not 0) when I try to store the result in a string. Is that the right type of variable to store that?
Could you maybe check to see if the variable is working? Not to doubt it of course but i'm not sure why that simple script wouldn't work. Thanks! :)

**Comment by YegorZaremba** [comment]
@lusseyarmet sry, I forgot about declaration `window.blockedItems = 0` - put it somewhere, maybe here https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/Filter.ts#L14

> Is that the right type of variable to store that?

as you please, but better to store number type

this var works
<img width="322" alt="Screen Shot 2020-10-02 at 7 04 45 PM" src="https://user-images.githubusercontent.com/31797554/94944593-24b69e80-04e2-11eb-9960-81bdf9a195a8.png">

**Comment by lusseyarmet** [comment]
@YegorZaremba Bit of a stupid question I imagine, sorry, but how do I add the extension to chrome again after editing the files in the _src > content_ folder? Basically, I edited the two files you mentioned after downloading the repo and unzipping it but how do I then use that as a chrome extension? I tried adding the "dist" folder as an unpacked extension since that's where the manifest is but it's saying it couldn't load the manifest for some reason. Am I doing that right?

**Comment by YegorZaremba** [comment]
@lusseyarmet pls fork repo, `npm ci` after that `npm run build` and that it

**Comment by lusseyarmet** [comment]
How could I forget that... my bad. I'm having an issue when running `npm run build`, however. Runs fine at first and then this happens. Those are the two lines are the ones that have "window.blockedItems" in them, the ones I edited.
I'm guessing there's something else I need to edit?

[Link to screenshot](https://ibb.co/WnhS9b3)

**Comment by YegorZaremba** [comment]
pls add `// @ts-expect-error` above

like
```
// @ts-expect-error
window.blockedAmount = 0
```

**Comment by lusseyarmet** [comment]
I did that, and it worked (I guess it bypassed the errors) but now weirdly enough, the extension itself just doesn't work anymore for some reason, it fails to hide images, nsfw or not (as when loading a page normally the filter hides all images and then only shows the one that are safe, here images are displayed normally, as though the extension wasn't on but it is)
I'm really not sure why, there's no reason for those two lines to have changed anything else.

**Comment by YegorZaremba** [comment]
@lusseyarmet sorry for bug, pls make `git pull` and re-change your logic with `window.blockItems`

**Comment by lusseyarmet** [comment]
So, just to be clear because I'm unsure what I should or shouldn't do now, is this what I need to do? Since these are all the steps you've told me to do.

0) Download the new version of the code (because of the changes you've made)
1) go to nsfw-filter-master\src\content\Filter
2) Edit Filter.ts so that I get this:
```
constructor (_logger: ILogger) {
    this.logger = _logger
    this.blockedItems = 0
	// @ts-expect-error
    window.blockedAmount = 0
  }
```
3) Then edit ImageFilter.ts so that I get this:
```
  private _analyzeImage (image: _Image): void {
    image._isChecked = true
    this.hideImage(image)
    this.logger.log(`Analyze image ${image.src}`)

    const request = new PredictionRequest(image.src)
    this.requestToAnalyzeImage(request)
      .then(({ result, url }) => {
        if (result) {
          // @ts-expect-error
          window.blockedItems++
        } else {
          this.showImage(image, url)
        }
      }).catch(({ url }) => {
        this.showImage(image, url)
      })
  }
```
4) run `npm ci` and then `npm run build`
5) Load this unpacked extension into chrome
6) Run `return window.blockedItems`

Is that it? Thanks!

**Comment by YegorZaremba** [comment]
@lusseyarmet looks great, pls make `git commit` & `git push` to your repo https://github.com/lusseyarmet/nsfw-filter and I'll check it by myself

**Comment by lusseyarmet** [comment]
Yeah, I think I'll wait until something better comes up or maybe I'll see if the future pop-up can help me in some way because I'm already in way over my head, I'm way too much of a newbie with GitHub and JS for this ^^
Thanks a lot for trying, though! :)
