### ISSUE TITLE
While video appear in website how it will read that means model will take (process ) video  thumbnail or  video frames? 

### ISSUE THREAD

**Issue by HemanthKumarGadi** [nsfw-filter/nsfw-filter#105]

**Comment by YegorZaremba** [comment]
Hi @HemanthKumarGadi filtering video under development https://github.com/infinitered/nsfwjs/issues/39#issuecomment-685324717

To be honest its even difficult to say how it will work 😄

**Comment by YegorZaremba** [comment]
Related #16
