### ISSUE TITLE
Summaries for classes and methods.

### ISSUE THREAD

**Issue by govza** [nsfw-filter/nsfw-filter#124]
I think that code lack of comments (jsdoc) thus hard to understand. Maybe should consider adding them at least for classes and public methods as part of project code-style?

#### Is your feature request related to a problem? Please describe.
Hard to understand what code does.

#### Describe the solution you'd like
JSDoc classes and public methods.

**Comment by YegorZaremba** [comment]
Great Idea!
For start I recommend:
- [Model](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/Model/Model.ts)
- [LRUCache](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/Model/LRUCache.ts)
- [ConcurrentQueue](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/PredictionQueue/ConcurrentQueue.ts)
- https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/background.ts

Other files may be refactored in recent future
