### ISSUE TITLE
Counting Blocked Items (Again)

### ISSUE THREAD

**Issue by lusseyarmet** [nsfw-filter/nsfw-filter#146]
Hi again!
Amazing job on the extension, 1.3.0 came out really fast!
However I have one question: reading an older post I was under the impression the extension popup would show # of currently blocked pictures in the active tab, and it seems to be counting the total # of blocked items instead. Just wanted to know if that was on purpose or not.
Also, is that variable still working? Would it be easier to access now, using 1.3.0 ?
(Because I don't think I can access the popup's data directly since it's a dynamic page.)

Thanks! :)

**Comment by YegorZaremba** [comment]
Hi @lusseyarmet we added `data-nsfw-filter-status` attribute to filtered images. Now when page is loaded you should wait for a while(f.e. 5 secs) and after that just call:
```js
const images = element.getElementsByTagName('img')
for (let i = 0; i < images.length; i++) {
    if (images[i].dataset.nsfwFilterStatus === 'nsfw') // image is NSFW

    if (images[i].dataset.nsfwFilterStatus === 'sfw') // image is SFW

    if (images[i].dataset.nsfwFilterStatus === 'processing') // image is on processing
}
```

**Comment by lusseyarmet** [comment]
That works perfectly! Thanks again.
