### ISSUE TITLE
Less Accurate Model (Less filtered images) in Version 1.3.0 as compared to 1.2.0

### ISSUE THREAD

**Issue by lusseyarmet** [nsfw-filter/nsfw-filter#147]
I read that the nsfw model was updated in 1.3.0 which would normally be a good thing since the nsfwmodel creator said it was more accurate but it doesn't seem to be nearly as accurate in my tests.

Looking at the # of images blocked when doing a simple google image search for "porn" using the old 1.2.0 extension that's still available on the Chrome Store, ALL of the actually NSFW images get filtered (3 images do show up but they aren't nsfw). 
Using the new 1.3.0 extension, however, 8 / 36 total images get through the nsfw filter, in addition to the 3 sfw images from before.

I've reproduced the lower accuracy in a few random pages with more nsfw photos popping up as well.
Now I'm not sure if that's a bug or if the newer model isn't as accurate as the creator thinks it is, but I just wanted to put it out there in case you guys can reproduce it and want to revert or whatnot ^^

**Comment by YegorZaremba** [comment]
Hi @lusseyarmet nice to see you :)

So you should `git pull`, change this line of code https://github.com/nsfw-filter/nsfw-filter/blob/master/src/popup/redux/reducers/settings.ts#L21 f.e. lets pick 85% strictness and `npm run build`

Old model has a lot of false positive results (related #93)

**Comment by lusseyarmet** [comment]
Ah okay, cool! Is there anyway I could change the model myself, though? Can I just delete the existing model and json (in the dist > models folder), then drag and drop the new model .bins and the model.json to that same folder and then run `npm run build` ?
Would that work?

**Comment by YegorZaremba** [comment]
@lusseyarmet take a look https://github.com/nsfw-filter/nsfw-filter/commit/059e468c6fcba65427d9fcfe335b0b32c52a2e5e
and if you would like to don't use strictness bar

https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/Model.ts#L76 replace this:
```
  private handlePrediction (prediction: predictionType[]): { result: boolean, className: string, probability: number } {
    const [{ className: cn1, probability: pb1 }, { className: cn2, probability: pb2 }] = prediction

    const result1 = this.FILTER_LIST.has(cn1) && pb1 > (this.firstFilterPercentages.get(cn1) as number)
    if (result1) return ({ result: result1, className: cn1, probability: pb1 })

    const result2 = this.FILTER_LIST.has(cn2) && pb2 > (this.secondFilterPercentages.get(cn2) as number)
    if (result2) return ({ result: result2, className: cn2, probability: pb2 })

    return ({ result: false, className: cn1, probability: pb1 })
  }
```

to old code in v1.2.0 I guess it was 0.5

**Comment by lusseyarmet** [comment]
So I simply installed the bigger web model and now it works great! 
Thanks :)
