### ISSUE TITLE
Update activity diagram

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#152]
Our [activity diagram](https://github.com/nsfw-filter/nsfw-filter/tree/master/demo/UML) is out of date

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Can we make it something a bit more interactive than adding it just to the readme? We have the domain so we can host it in our website. I do not know the specifics but it seems like something we can do.

**Comment by YegorZaremba** [comment]
Great idea, I'll just add `Documentation` section in `Readme.Development` where put link to https://docs.nsfw-filter.com/

**Comment by navendu-pottekkat** [comment]
@YegorZaremba  That looks good.

**Comment by YegorZaremba** [comment]
Done
