### ISSUE TITLE
filter strictness doesn't appear to work on edge 

### ISSUE THREAD

**Issue by Gother01** [nsfw-filter/nsfw-filter#153]
the blocked results are the exact same number with no strictness or 100% 
used "porn" as the search term on google images 
model: mobilenet v1.1
filter effect didn't seem to have any impact on the end results, stayed the same number of blocked elements no matter what.

**Comment by YegorZaremba** [comment]
Hi @Gother01 hmmm.. Thanks for your report. Will check it out. Added to v1.4.0

**Comment by YegorZaremba** [comment]
@all-contributors please add @Gother01 for bug
