### ISSUE TITLE
Hide/block twitter nsfw content on incognito mode (without the need to login)

### ISSUE THREAD

**Issue by Catman847** [nsfw-filter/nsfw-filter#159]
#### Is your feature request related to a problem? Please describe.
Extension failed to block nsfw images and videos on twitter when using incognito mode

#### Describe the solution you'd like
Block all nsfw on twitter without login in aka using incognito mode

#### Describe alternatives you've considered
There are no alternatives to the feature I am suggesting, I have looked every where on the internet.

#### Additional context
Please do it. lol

**Comment by navendu-pottekkat** [comment]
@Catman847 Did you enable the extension in incognito mode?

You can do it by-

Click the menu button in Chrome.
Navigate to More Tools > Extensions.
In the new tab that opens, scroll through the list to find the extension you want to enable while incognito.
Click details > Click the “Allow in Incognito” button.
