### ISSUE TITLE
User issue: Failing to block images

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#160]
Some recent reviews in [Chrome Webstore](https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh) say that they are having issues and the filter is failing to block the images. We do not have many details but we need more testing and check if there are bugs.

Screenshot below-

![Screenshot from 2020-12-20 10-47-55](https://user-images.githubusercontent.com/49474499/102705798-640ab500-42b1-11eb-8f5b-2f25631e60d4.png)

Will update this thread if we get any more details from the users.

**Comment by YegorZaremba** [comment]
Please open a new issue for related bugs/questions
