### ISSUE TITLE
Another pre trained model onto this plugin 

### ISSUE THREAD

**Issue by kiran-collab** [nsfw-filter/nsfw-filter#164]
How to put another pre trained model of mine instead of MobileNet, leaving all features as it is. Do I need to change anything for that? Request to address the query as soon as possible.

**Comment by YegorZaremba** [comment]
Hi @kiran-collab 
Please take a look into this PR https://github.com/nsfw-filter/nsfw-filter/pull/111/files
It shows migration to an another ML model

**Comment by kiran-collab** [comment]
@YegorZaremba So I have replaced the  model.json file and its bin files (of my pretrained model) in the models folder.
and then I have again added all the dependencies and run the add on. This time it doesn't work. 
Can you please walk me through any other editions to be done!

**Comment by YegorZaremba** [comment]
hi @kiran-collab 

Probably, you should remove `type: graph` [here](https://github.com/nsfw-filter/nsfw-filter/pull/111/files#diff-b11fba3fe7b52728b021cbda8505a4dc695a5606d723001ac8f5ec854402cf17R34)

Recently I updated codebase to tenserflow 2.6.0, maybe it's a reason of the problem, try `1.3.0` tag

**Comment by kiran-collab** [comment]
@YegorZaremba Hey! The plugin is working. The thing when I am putting another ML model i.e. change the model.json files, I have to add the dependencies. I am really thankful to you! Incase any issues i would ping you!
Btw, do you know of any plugin architecture of this sort that blocks videos in this manner?

**Comment by YegorZaremba** [comment]
Hi @kiran-collab 
Wingman has added some video filtering stuff recently
https://github.com/wingman-jr-addon/wingman_jr/pull/93

**Comment by wingman-jr-addon** [comment]
(As an update, the video work has been merged into master and now been released in 3.0.0!)

**Comment by YegorZaremba** [comment]
Looks like question, please open a new issue for related bugs/questions
