### ISSUE TITLE
Add an alert box when nsfw images found

### ISSUE THREAD

**Issue by abhirammltr** [nsfw-filter/nsfw-filter#17]
## Expected Behavior
It should show an alert box when nsfw images detected. 
## Current Behavior
No alert. Extension will automatically filter nsfw images.

## Edit
What @abhirammltr is talking about is that when the user enters a website, we check the images in the website as soon as it loads and gives an alert to the user saying that we have found NSFW content on it. The user could go back or continue to the website.

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @abhirammltr as code, bug, ideas

**Comment by YegorZaremba** [comment]
Hi @abhirammltr, thanks for your contribution, could you please talk more, which kind of alert you expect to see? We have some discussion about it [here](https://github.com/navendu-pottekkat/nsfw-filter/issues/10#issuecomment-664365247)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba What @abhirammltr is talking about is that when the user enters a website, we check the images in the website as soon as it loads and gives an alert to the user saying that we have found NSFW content on it. The user could go back or continue to the website.

**Comment by YegorZaremba** [comment]
Get it, so how I get it, if website has more than for example 10 unsafe items, we display huge alert which covering whole page?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba It would be the default browser alert box. It will just show on top of the page like the one below.

![](https://www.oreilly.com/library/view/javascript-jquery/9781491948583/httpatomoreillycomsourceoreillyimages2120678.png.jpg)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Please join this slack channel https://join.slack.com/t/nsfwfilter/shared_invite/zt-gfx0dewg-Hc0~3gu4jXcCDYWQxu3lZA

**Comment by ClayMav** [comment]
Alternative approach could be to consider this extension not so much as a parent, blocking access to sites with adult content, but just as a way to not have to see the content (so often)

Under that idealogy, instead of halting the user, we could pop it from the extension icon as a warning that doesn't need to be dismissed just to let them know

**Comment by navendu-pottekkat** [comment]
> Alternative approach could be to consider this extension not so much as a parent, blocking access to sites with adult content, but just as a way to not have to see the content (so often)
> 
> Under that idealogy, instead of halting the user, we could pop it from the extension icon as a warning that doesn't need to be dismissed just to let them know

@abhirammltr This looks like a good idea. Could we try something like this in the popup you are currently building?

**Comment by YegorZaremba** [comment]
Yeah, same thought, I dont like when sth told me what to do, and also I dont like all these parent relative app with PINs and etc
I suggest to sth like Google/Youtube/Twitter ![](https://help.twitter.com/content/help-twitter/ru/using-twitter/url-shortener/_jcr_content/yang/image.img.png/1511833039973.png)

with 2 options `go back` and `stay on page`

**Comment by ClayMav** [comment]
I think the reason Google, Twitter, and Facebook do that is because they don't protect their users on those pages, and that's where this extension differs. Ideally it should be safe to even look on many porn sites with the extension installed

**Comment by YegorZaremba** [comment]
> Ideally it should be safe to even look on many porn sites with the extension installed

Exactly! It definitely what I want (as you see I'm not a creator of this issue :smile: )

**Comment by navendu-pottekkat** [comment]
@ClayMav @YegorZaremba So could we drop the alert idea and go with this instead?

**Comment by YegorZaremba** [comment]
I dont want see any alerts, cause its easy, just alert whole page and dont allow user to see any stuff. I would like that this extension do more focus on ML model and filtering. Upvote for drop alert idea

**Comment by navendu-pottekkat** [comment]
> Alternative approach could be to consider this extension not so much as a parent, blocking access to sites with adult content, but just as a way to not have to see the content (so often)
> 
> Under that idealogy, instead of halting the user, we could pop it from the extension icon as a warning that doesn't need to be dismissed just to let them know

@YegorZaremba this idea right? I upvote

**Comment by YegorZaremba** [comment]
I upvote but with ability to turn off this popup in popup menu :D
