### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by hindmost** [nsfw-filter/nsfw-filter#172]
Guys, I like your extension it's nice. But I don't like that you [copied](https://github.com/nsfw-filter/nsfw-filter/tree/master/src/popup/redux/chrome-storage) the sources of [my library](https://github.com/hindmost/reduxed-chrome-storage) without any attribution to me or my repo at least. Even being opensource you may not do so - my license prohibits it. You have to put some link to my library's repo somewhere in your sources (or in README). Or you can just include my library as Node dependency (`npm install reduxed-chrome-storage`) - it would be enough for settlement.

**Comment by YegorZaremba** [comment]
Hi @hindmost Im so sorry, I would like to dive deep with you lib and forgot to install it. I'll fix it today/tmrw and add your lib in our Readme for potential PR <3

**Comment by hindmost** [comment]
BTW/FYI, the latest version of my library (2.0.0) supports TypeScript. so allowJs option in your tsconfig is unnecessary now.

**Comment by YegorZaremba** [comment]
Fixed
Thanks for the library
It would be great to be able to export helper types  https://github.com/nsfw-filter/nsfw-filter/blob/master/src/popup/redux/chrome-storage/index.ts#L12

**Comment by hindmost** [comment]
@YegorZaremba Thanks for noting, I missed that point. Maybe I better change the function signature to use `string` type for `storageArea` param, instead of helper type (`StorageAreaName`)?

**Comment by hindmost** [comment]
Just FYI. I changed/fixed TypeScript definition in the function signature. Now it won't produce that error. Update my library to 2.0.5 in your package.
