### ISSUE TITLE
How to use some other pre trained model?

### ISSUE THREAD

**Issue by neel1998** [nsfw-filter/nsfw-filter#176]
I want to use another pre trained model as the backend model for this extension. How can I do that?

**Comment by navendu-pottekkat** [comment]
Hi @neel1998 please refer issue #164

**Comment by neel1998** [comment]
How do I create the .json and .bin files?... Should I just use tf.save()?

**Comment by navendu-pottekkat** [comment]
If you are using a TF Keras model you can convert it to TFJS format. Refer
https://www.tensorflow.org/js/guide/conversion

**Comment by YegorZaremba** [comment]
Looks like question, please open a new issue for related bugs/questions
