### ISSUE TITLE
Bunch of False positives

### ISSUE THREAD

**Issue by Ashish0804** [nsfw-filter/nsfw-filter#186]
#### False Positives

Having a bunch of false positives for workspace images
#### Expected result

It shouldn't blur/hide them
#### Actual result

It's blurring/hiding them
#### Steps to reproduce

1. Set strictness to max with default model
2. Go to https://boards.4channel.org/g/thread/82991211
3. Wonder why it's happening and curse black box models
#### Context

It isn't affecting me in any serious way -_-
Just reporting here out of curiosity.
I don't see what would trigger false flagging here. I am assuming NSFW images usually have curves and are biased towards lighter colors so don't see how 
#### Your Environment

* Version used: v1.3.0
* Browser Name and version: brave v1.28.105
* Operating System and version: PopOS 20.04
* Link to your project: NA

Images:
![image](https://user-images.githubusercontent.com/39122144/129943312-99a5ee98-f102-43ff-8f4e-2dc450dde76c.png)
![image](https://user-images.githubusercontent.com/39122144/129943350-d56216d9-75e2-436a-9635-5f19b5864912.png)
![image](https://user-images.githubusercontent.com/39122144/129943398-721e32a9-bfc4-4d57-8f71-fe3fdb9b7186.png)
![image](https://user-images.githubusercontent.com/39122144/129943447-59d2fb5a-38d1-442a-923c-8d8e7bda4ccc.png)
![image](https://user-images.githubusercontent.com/39122144/129943480-af06a221-56c8-4375-9c9f-134e112acd32.png)

**Comment by navendu-pottekkat** [comment]
Thank you for reporting the issue @Ashish0804 . We are planning to build a better model tailored specifically for Internet/ Browsing. The ETA of this is not quite sure but we definitely need to fix this.

**Comment by Ashish0804** [comment]
@navendu-pottekkat inspired by this project...and frustrated with false positives 😅 
I decided to choose this as my final year project.

I used efficientnetv1 as backbone with imagenet weights and have got fairly decent results.
I'll soon make the models public (with an efficientnetv2 in pipeline as well)
Hopefully my models can be used with this extension 🤞 

P.S. the data is imgur, reddit and pornpics
Ideally I'd like to train with a million (around 1TB) images but current testing is being done with 10k images and then another model trained with 70k images.

**Comment by navendu-pottekkat** [comment]
That is awesome to hear! We can add multiple models and if what you build performs well, feel free to contribute to it here!

**Comment by YegorZaremba** [comment]
Hi @Ashish0804 
Sorry for that, this issue related to https://github.com/infinitered/nsfwjs/issues/324

Try to play with strictness

![image](https://user-images.githubusercontent.com/31797554/167242010-8bea366a-2a0c-469e-8524-73ce82e99e98.png)
