### ISSUE TITLE
No longer available in the Chrome Webstore

### ISSUE THREAD

**Issue by Geo25rey** [nsfw-filter/nsfw-filter#198]

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Seems like we are asking for more permissions than needed and the Chrome webstore might have blocked the extension.

**Comment by litmount** [comment]
Seems chrome is reporting it as malware...
![image](https://user-images.githubusercontent.com/13424401/145830370-08605e35-e342-4f18-a96f-d690ded7b838.png)

**Comment by navendu-pottekkat** [comment]
Yep. I think it is because we ask for more permissions than we need...

**Comment by YegorZaremba** [comment]
It will be fixed in the nex release with
https://github.com/nsfw-filter/nsfw-filter/issues/199
https://github.com/nsfw-filter/nsfw-filter/issues/197

I hope I get a few days in the Christmas for it

**Comment by litmount** [comment]
@YegorZaremba Any update on this? It's still not on the store?

**Comment by csgosmorf** [comment]
To anyone who is not a programmer, this program is utterly useless if it can't be installed in the chrome extensions page and there is not a how-to guide on installing it on this repo. It really narrows the target audience to a crazy degree. This should be the top priority by far imo, unless you're just developing it for the developers themselves.

**Comment by navendu-pottekkat** [comment]
@csgosmorf @litmount This project is entirely free and open source. We started this project two years ago and we do not have enough time now to continue maintaining the project. We are trying our best to find time to work on the project and get a stable release out.

If @YegorZaremba is available to fix this, we will get a working version on the store soon.

We will also try to get new maintainers who can continue to steward this project.

**Comment by YegorZaremba** [comment]
@Geo25rey @litmount @csgosmorf now you can download it https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh/related
