### ISSUE TITLE
Add option for the user to choose how to filter the images

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#2]
## Expected Behavior

The user should be able to select how the image should be filtered from the following options:

* Replace with an image from Unsplash
* Blur image
* Replace image with custom image
* Add watermark to the image
* Do nothing/ turn off filter

## Current Behavior

Currently, if the images are found to be NSFW, they are automatically replaced by images from Unsplash.

## Possible Solution

Add a ```popup.html``` file for the popup and add different options.

Based on this option change how the image would be processed in ```content.js```

**Comment by navendu-pottekkat** [comment]
This feature has been implemented in the feature update branch and would be available in the next release.

However a UI for this has not been created

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Should we add the watermark feature?

**Comment by YegorZaremba** [comment]
Yeap, like option(maybe even default choice) in the popup, but we need a design for watermark

**Comment by navendu-pottekkat** [comment]
@YegorZaremba ask for help "help wanted" maybe? This could also be a good first issue

**Comment by YegorZaremba** [comment]
Sure, thanks)

**Comment by YegorZaremba** [comment]
done https://github.com/nsfw-filter/nsfw-filter/pull/110 user can choose between `hide` and `blur`
