### ISSUE TITLE
can you add this nsfw images?

### ISSUE THREAD

**Issue by keroberos-s** [nsfw-filter/nsfw-filter#200]
#### Bug description

not filtered this imgs even nsfw

i.imgur.com/ZHb3pTa.jpg
i.imgur.com/HKeEkSM.jpg
i.imgur.com/dXNiYLc.jpg

and i think download isn't not work https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh

* Version used: 1.3.0
* Browser Name and version: Opera GX / LVL3 (core: 82.0.4227.50)
* Operating System and version: Windows 10 / 20H2 (OS bulid 19042.746)

**Comment by YegorZaremba** [comment]
@keroberos-s Thanks for your bug report, now you can download the extension from the link above :heart:

**Comment by YegorZaremba** [comment]
Hi @keroberos-s 
Sorry for that, this issue related to https://github.com/infinitered/nsfwjs/issues/324

Try to play with strictness 
![image](https://user-images.githubusercontent.com/31797554/167241542-556d48bc-3595-4c42-ab17-a8f57056d4c8.png)
