### ISSUE TITLE
Hardware acceleration breaks the filter

### ISSUE THREAD

**Issue by sensitivecereal** [nsfw-filter/nsfw-filter#208]
Hardware acceleration breaks the filter

#### Bug description
When "Use hardware acceleration when possible" is enabled in Chrome, the filter suddenly stops working.

#### Expected result
Filter should still work.

#### Actual result
Filter doesn't filter out anything, everything is considered sfw.

#### Steps to reproduce

1. Go to Chrome settings -> Advanced -> System
2. Enable "Use hardware acceleration when available"
3. Test filter

**Comment by wingman-jr-addon** [comment]
Hi @sensitivecereal !  With the Tensorflow.js usage, it's also helpful to know about the hardware setup. So maybe a couple questions to help triage things here for folks:

1. Does this happen on every computer you try it on or just one? Ideally try one with a better video card and one without.
2. Can you post video card setup for the one that's not working? I can't remember if Chrome has a way to get this info like Firefox but that type of dump is useful if it ends up being a Tensorflow.js issue.

As folks get into it, the Tensorflow.js environment variables may also end up being important to get, but that's probably a later step.

**Comment by sensitivecereal** [comment]
Okay, so I somehow fixed it.
It was either:
1. Going into the NVIDIA Control Panel and setting chrome.exe to specifically use my discrete GPU for WebGL.
2. Going into the Windows 10 Graphics settings and setting chrome to use my discrete GPU.
My bad.

**Comment by wingman-jr-addon** [comment]
@sensitivecereal  That's actually probably a thing that either the Chrome team or the Tensorflow.js team might be interested in (assuming it's something deeper). Can you get the issue to reoccur if you flip back to the other GPU?
