### ISSUE TITLE
Dead link for Firefox extension

### ISSUE THREAD

**Issue by zeref-dragneel** [nsfw-filter/nsfw-filter#211]
Link [nsfw-filter.com](https://addons.mozilla.org/en-US/firefox/addon/nsfw-filter/) shows 404 error "Oops! We can’t find that page".

![ảnh](https://user-images.githubusercontent.com/95934994/164988276-c29af451-39ee-4834-ba8e-261e276d541c.png)

<details>

![ảnh](https://user-images.githubusercontent.com/95934994/164987952-354f3c4e-67b4-4b92-867d-86004b756ffb.png)

</details>

**Comment by navendu-pottekkat** [comment]
@zeref-dragneel Firefox stopped supporting some features and we had to take it down from the store because it was no longer working. Will update the site. New version for Chrome was submitted today.

**Comment by bmaupin** [comment]
> @zeref-dragneel Firefox stopped supporting some features and we had to take it down from the store because it was no longer working.

@zeref-dragneel Is this something that could be remediated or would it be better looking elsewhere, e.g. https://github.com/wingman-jr-addon/wingman_jr

Thanks!
