### ISSUE TITLE
Unsplash srolled images become visible after few seconds

### ISSUE THREAD

**Issue by toropanov** [nsfw-filter/nsfw-filter#225]
#### Bug description
If I go to https://unsplash.com/collections/RR306Lrrx6M/summer-bikini with enabled extension (strongest filter) than scroll to bottom (with press load more). Then after few second I stop scroll on end - bottom images appearing.

#### Expected result
Images stays hidden

**Comment by toropanov** [comment]
That's actually on every websites. Esspecially on unsplash. If you scroll top and bottom fast - hidden images appearing then.

**Comment by yzevm** [comment]
@toropanov thanks, I'll check it out :+1:

**Comment by toropanov** [comment]
Looks like I understood what's happened. That's my fall I guess. Bug can be marked as resolved.

But I would suggest features:
1) Remove option in Filter effect. That's will remove it from DOM
2) PIN Code
3) Sync theme dark / light depends on system
