### ISSUE TITLE
Whitelist certain websites

### ISSUE THREAD

**Issue by michaelmannucci** [nsfw-filter/nsfw-filter#245]
#### Is your feature request related to a problem? Please describe.
False flags for websites you know have no NSFW images. Would be good to whitelist certain websites. I am a dev, and when desinging pages, it is blurring certain images which can be frustrating while developing.

#### Describe the solution you'd like
Add a url that will bypass the plugin

#### Describe alternatives you've considered
Disabling it?

**Comment by navendu-pottekkat** [comment]
@michaelmannucci Thank you for the suggestion. Would you be interested in working on this feature?

**Comment by michaelmannucci** [comment]
No idea how to

**Comment by navendu-pottekkat** [comment]
@michaelmannucci I have added this feature in #248

Could you help review and share suggestions?

Also consider supporting this project by sponsoring on [Patreon](https://www.patreon.com/nsfwfilter) or [GitHub](https://github.com/sponsors/navendu-pottekkat).
