### ISSUE TITLE
Landed extension on chrome webstore

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#25]
## Expected Behavior

Extension landed on https://chrome.google.com/webstore/category/extensions

## Current Behavior

There is no extension

**Comment by navendu-pottekkat** [comment]
Got the developer account. Will publish v1.0.0 on Firefox store and Chrome store

**Comment by navendu-pottekkat** [comment]
Submitted to Firefox and waiting for review in Chrome store

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Chrome has quite strict permission policies. Could you check if all the permissions are required for your code to work?

**Comment by YegorZaremba** [comment]
Do we have any updates?

**Comment by navendu-pottekkat** [comment]
It is still in review. Maybe because we have so many permissions. They said that it could take a month and this seems the only way to land the extension on the store. I will update when we get a reply. We might have to resubmit after changing the permissions.

**Comment by YegorZaremba** [comment]
Landed https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh?hl=en

**Comment by navendu-pottekkat** [comment]
I did not know that they published. They could have sent a mail
