### ISSUE TITLE
V1.0.0 Release

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#30]
V1.0.0 is now officially complete. Let's look into how we can share this project with a more broad audience to get more awesome ideas and features. Here are some of the things I would like to check:

- [x] Check documentation
- [x] Manual testing
- [x] Social media posts
- [x] Releasing on Firefox and Chrome addons store

**Comment by YegorZaremba** [comment]
Awesome, do you have any date when you planning to upload extension to firefox addons and chrome webstore?

I think sample of marketing post is helpful to reach new users on social media like `reddit, 4chan and etc`

**Comment by navendu-pottekkat** [comment]
@YegorZaremba How about we release it tomorrow?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba We will follow these guides:

https://hackernoon.com/how-to-promote-your-github-project-1b39a7eee841
https://medium.com/free-code-camp/how-to-get-up-to-3500-github-stars-in-one-week-339102b62a8f

What we can do is write an article about the project and share it in these platforms.

**Comment by navendu-pottekkat** [comment]
Updated the latest version in Firefox Add-ons store: https://addons.mozilla.org/en-US/firefox/addon/nsfw-filter/

Waiting for approval from the chrome store.

**Comment by YegorZaremba** [comment]
So late, but what do you think about name? `nsfw-filter`, I mean we do similar thing as `AdBlock`, but for nsfw content, maybe `NSFWBlock` or sth with `block` is better for future marketing/promotion?
In my world block > filter :smile:

**Comment by navendu-pottekkat** [comment]
They both convey the same purpose right? First it was actually NSFW Block but I changed it to filter. This would work well if in the future we are giving the user more filtering options. @YegorZaremba How are the tests going? I think things are looking good. I have update the docs and now I have to make writeups for sharing the project

**Comment by YegorZaremba** [comment]
Get it, I use our extension(and love it), looks there aren't huge troubles, maybe few memory leaks, but for v1.0.0 - its fine

**Comment by navendu-pottekkat** [comment]
@YegorZaremba What time should we release? I would say around 9:00 PM IST? I have setup the articles and would go through a check once again.

**Comment by navendu-pottekkat** [comment]
Product Hunt Link: Sheduled for release at 9:00 AM PT https://www.producthunt.com/posts/nsfw-filter/maker-invite?code=wNxkjN

**Comment by navendu-pottekkat** [comment]
@YegorZaremba All set for the release. You also share in every channel you can find. I will share it in 1hr from now. I will share the links to the post after that.

**Comment by navendu-pottekkat** [comment]
https://madewithml.com/projects/2008/extension-to-block-nsfw-content-using-ai/

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Share away! I have very low reddit Karma after I lost my old account. Post on r/javascript and r/webdev

**Comment by navendu-pottekkat** [comment]
Extension to block NSFW images using AI! 

#AI #ArtificialIntelligence #MachineLearning #webdev #Chrome #ComputerVision #DataScience #OpenSource #programming #programmer #code  #javascript #TensorFlow #keras #Python #github #productivity #product  

https://github.com/navendu-pottekkat/nsfw-filter

**Comment by navendu-pottekkat** [comment]
@YegorZaremba https://www.reddit.com/r/javascript/comments/i0nmbe/nsfw_filter_block_nsfw_content_using_ai/

**Comment by YegorZaremba** [comment]
yeah boy, awesome! ( upvoted :smile: )

**Comment by navendu-pottekkat** [comment]
> yeah boy, awesome! ( upvoted  )

@YegorZaremba You also share in every possible place as in the article you shared. This should be blowing up by tomorrow! (I wish)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba while you are sharing, I would suggest you use the working GIF image and provide link to the repo. What do you think?

**Comment by YegorZaremba** [comment]
lemme fix #31 and when we landed on chrome webstore, I'll start to promote too :rocket:

Yeah gifs is do a lot clarification of what's going on, awesome idea :+1:

**Comment by YegorZaremba** [comment]
Looks like v1.0.0 is done

**Comment by navendu-pottekkat** [comment]
I did not get notified when the published it in the Chrome Store
