### ISSUE TITLE
Remove redundant permissions from manifest.json

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#31]
## Expected Behavior

Only require permissions that are necessary.

## Current Behavior

Some permissions are redundant and are not being used.

## Possible Solution

Check all the permissions in the manifest and check if they are being used and are really necessary.

## Context

Redundant permissions without any uses could get the extension removed from the Chrome Webstore.

version: v1.0.0

**Comment by YegorZaremba** [comment]
taken, will fix in 12hr

**Comment by YegorZaremba** [comment]
I guess we have done because of `v1.2.0`
