### ISSUE TITLE
Extension is slowing down page load on https://pr0gramm.com/

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#35]
## Expected Behavior

* The extension should not cause any lag and with our testing, **it does not cause any lag**. Need to test if this is a legitimate issue.

* Smaller images should also be checked.

## Current Behavior

One user tested the extension out on a German imageboard https://pr0gramm.com/ and found that using the extension is causing the page to load significantly slower.

Also, the smaller images on the page were unfiltered.

>I did test it on Reddit and a German imageboard that lists it content in 128x128 thumbnails within a grid. The NSFW section is for members only though =/

> That's the site where I had most problems with images not being blocked. So I guess the AI doesn't seem to be trained well enough for such small images. This was the site with the longest loading times, but that site would probably be the worst case for this extension. I think another reason for the long loading times is the XHRs that load the images on that site which also leads to the problem of images being displayed before they eventually are blocked.

## Steps to Reproduce (for bugs)

Check the website mentioned in the issue.

## Solutions
* The extension should be checked if it is causing any slowing down.
* #32 Should be fixed.

**Comment by YegorZaremba** [comment]
Got it, what about you? do have some lags on this website?

**Comment by navendu-pottekkat** [comment]
I don't find it laggy though. Like I don't think we are the reason for the slow load. Like it works on Google Images perfectly right? Even if we keep scrolling.

Anyway, we will keep it open and see if anybody else is having any issues.

**Comment by navendu-pottekkat** [comment]
I have tested the extension on multiple sites for a couple of days. Apart from the initial lag as mentioned in #19 there does not seem to be any performance issues. The additional lag on the site https://pr0gramm.com/ might be because of the XHRs as mentioned by the user. 

If anybody is facing any issues, comment below.

**Comment by YegorZaremba** [comment]
Tested
I have some lags because there are a lot of images, but every image is analyzed
Seems like just performance improvement
