### ISSUE TITLE
Add a landing page

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#41]
Add a landing page for our extension. A simple one-page website should be enough. 

Currently, the default README file in docs/ folder is used for creating the website. 

Should we add this?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba What do you think?

**Comment by YegorZaremba** [comment]
Yeah, why not, more links and references => more percentages for [pageRank](https://en.wikipedia.org/wiki/PageRank) algorithm => more users. For domain we can use [github pages](https://pages.github.com/)
Do you would like to do it?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba I will take it. But to make it better we have to get a new domain. currently it is navendu.me/nsfw-filter. Is this enough or should we get a new one?

**Comment by YegorZaremba** [comment]
I mean its better to use default free `github pages` url like `http://username.github.io/repository` (`http://navendu-pottekkat.github.io/nsfw-filter`) because it already a `github.io` domain which is more ranked than our any new domain

**Comment by navendu-pottekkat** [comment]
but http://navendu-pottekkat.github.io is navendu.me

**Comment by YegorZaremba** [comment]
Get it, okey, so Im fine with any domain :smile:

**Comment by navendu-pottekkat** [comment]
Like should we add nsfwfilter.com or something like that? They also get good SEO rank

**Comment by YegorZaremba** [comment]
Not sure about availability/price of any domain like that, but why not, we can try to find good one

**Comment by YegorZaremba** [comment]
[Done](https://github.com/nsfw-filter/nsfw-filter.com/commit/45b76879d76b7e1151da7fa5c0f1db3365c3f924)
