### ISSUE TITLE
Filter div with backgorund image

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#46]
#### Bug description
If page has `div` element with `background-image`, we should filtered it too

```html
<div style="background-image: url('https://example.com/image.jpg')"></div>
```

#### Expected result
Should be filtered

#### Actual result
Nothing is filtered

**Comment by dyaskur** [comment]
Why on v1.3 this code deleted?

**Comment by dyaskur** [comment]
If it's performance reason, I submitted PR that I think has better performance.

Tested on this link :

https://www.blibli.com/p/women-sexy-bikini-triangle-color-stripe-lace-up-bra-panties-briefs-underwear-set/ic--BLS-60040-47162-00001
