### ISSUE TITLE
Reverse filtering ie. only nsfw images

### ISSUE THREAD

**Issue by Zopieux** [nsfw-filter/nsfw-filter#52]
#### Is your feature request related to a problem? Please describe.
Not a problem, just a thought. Following up on #2, would it be possible to add a toggle so the extension *only shows NSFW content*? That could come in handy to hide all the crap on some sites.

#### Describe the solution you'd like
An opt-in option to reverses the filtering ie `if (nfsw)` → `if (!nsfw)`. The rest remains untouched.

#### Describe alternatives you've considered
Status quo.

**Comment by navendu-pottekkat** [comment]
@Zopieux Aha! Although that is out of the scope of this project, you can do that by just changing an if statement. But I guess we won't be adding that in here.
