### ISSUE TITLE
DeepFakes clean images

### ISSUE THREAD

**Issue by bradydowling** [nsfw-filter/nsfw-filter#53]
#### Describe the solution you'd like
Usage of DeepFakes type changes to an image but to clothe people. 

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

**Comment by navendu-pottekkat** [comment]
Currently, the ML model used just can classify the images as NSFW or not. It cannot localise or detect what exactly is the NSFW part. Maybe with an another model we can try.

**Comment by bradydowling** [comment]
Makes sense. This would definitely not be a first issue kind of thing. It would require significant changes but just thought I'd mention the idea.

**Comment by navendu-pottekkat** [comment]
@bradydowling Any and all ideas are great. We can think of something like this after we have fixed everything with this. Maybe we can train a new model but that requires a lot of resources. So this could be something we can look at in the future.

@all-contributors please add @bradydowling for ideas

**Comment by YegorZaremba** [comment]
Hard to implement, wontfix in 2020 and 2021 I guess
