### ISSUE TITLE
Ability to choose filter strictness

### ISSUE THREAD

**Issue by bradydowling** [nsfw-filter/nsfw-filter#58]
#### Is your feature request related to a problem? Please describe.
No.

#### Describe the solution you'd like
The extension could have a setting which is a scale, for example 1-100, that allows you to set how strict the filter should be. I believe the process that classifies an image as NSFW also has a confidence rating on it so you could basically allow users to choose how confident they'd like it to be.

#### Describe alternatives you've considered
- Allow users to mark an image on the page as NSFW, thus adding new training data to the model locally

#### Additional context
N/A

**Comment by navendu-pottekkat** [comment]
@bradydowling That seems like a good idea. Currently, we are not considering the confidence level and only checks if the top prediction is considered as NSFW(porn, hentai, sexy). We could definitely look into this. @YegorZaremba what do you think?

**Comment by YegorZaremba** [comment]
Hi @bradydowling thanks for contributing

Yeah I also think about it, its definitely one of the thing which we should add

@navendu-pottekkat What do you think about adding simple adjust bar in `popup` menu for `v1.2.0`?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba We can leave that for v1.3.0, I think since we have to get v1.2.0 out there especially for Chrome since it is in v1.0.0 right now. So I think the popup would be best for the next release. We can also look into a good design for the popup. But I really like this idea and we should implement it
