### ISSUE TITLE
failed to hide images

### ISSUE THREAD

**Issue by garfieldbanks** [nsfw-filter/nsfw-filter#60]
#### Bug description

failed to hide all nsfw images

#### Expected result

all nsfw images should be hidden

#### Actual result

some nsfw images were not hidden

#### Steps to reproduce

1. go to bing.com
2. search for "nsfw"
3. click images
4. turn off safe search
5. scroll down to find images that were not properly hidden by the extension

#### Context

i like the idea of the extension and would like it to be improved

#### Your Environment

* Version used: 1.0
* Browser Name and version: chrome 85
* Operating System and version: windows 10
* Link to your project: n/a

**Comment by TitusRobyK** [comment]
This is an Invalid bug or unable to replicate the issue

**Comment by TitusRobyK** [comment]
![image](https://user-images.githubusercontent.com/32787952/91258241-8cfabd80-e789-11ea-91c3-76e4f54b91bc.png)

**Comment by garfieldbanks** [comment]
you need to scroll down

i would post a screenshot, but ya know it's nsfw

**Comment by TitusRobyK** [comment]
![image](https://user-images.githubusercontent.com/32787952/91258444-f8dd2600-e789-11ea-870f-40fc0edc0410.png)
Nope , still not happening

If you notice the scroll bar , its small

**Comment by garfieldbanks** [comment]
this is the first one that i see (there are many more):
th.bing.com/th/id/OIP.djsoeg1Wo3uOQAY4TI2zKgHaEK?w=194&h=109&c=7&o=5&pid=1.7

**Comment by navendu-pottekkat** [comment]
@garfieldbanks Could you check if the extension is turned on by navigating to ```chrome://extensions/```?

**Comment by garfieldbanks** [comment]
it blocks most of them so i know it is working

**Comment by TitusRobyK** [comment]
@garfieldbanks 
tried the URL that you provided

![image](https://user-images.githubusercontent.com/32787952/91258799-da2b5f00-e78a-11ea-8e37-16b43a165000.png)

**Comment by garfieldbanks** [comment]
so the bug is that when i installed this extension from the chrome app store, some of the images don't get blocked

**Comment by garfieldbanks** [comment]
Can I provide any more information to help?

**Comment by garfieldbanks** [comment]
> @garfieldbanks Could you check if the extension is turned on by navigating to `chrome://extensions/`?

yes it is enabled

**Comment by navendu-pottekkat** [comment]
> so the bug is that when i installed this extension from the chrome app store, some of the images don't get blocked

@garfieldbanks We have the 1.0.0 version in Chrome. We will release the 1.2.0 version tomorrow. But that should not affect the image blocking. I think it may have to do with the fact that in the earlier versions, we excluded smaller images. But it was fixed in version 1.1 and it was not made available in Chrome as it took a long time for it to get reviewed in the webstore. 

But with tomorrow's release, it should be fixed.

@TitusRobyK What version did you check it with?

**Comment by garfieldbanks** [comment]
oh sorry i just assumed had the latest version cause i just downloaded it

**Comment by garfieldbanks** [comment]
ill try again tomorrow when the new release comes out

**Comment by navendu-pottekkat** [comment]
> oh sorry i just assumed had the latest version cause i just downloaded it

@garfieldbanks I am thinking that maybe the issue. I tried it with the version from Chrome store and it was not filtered. I will check with the latest version.

**Comment by navendu-pottekkat** [comment]
> ill try again tomorrow when the new release comes out

You can install from source and try it now. The master branch is at v1.1.0 but I guess it is better to wait till tomorrow.

**Comment by navendu-pottekkat** [comment]
It could be also that the model may have failed to classify the image as NSFW. It is prone to errors but it has 90% + accuracy

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @garfieldbanks for bug

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @TitusRobyK for bug

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @TitusRobyK for bug

**Comment by garfieldbanks** [comment]
I tried to install it by from source but it has errors:
![image](https://user-images.githubusercontent.com/12904270/91266625-e2ee4780-e72e-11ea-9359-68b23aff239d.png)

It also fails a lot more than the 1.0 version did when I test it on bing.

**Comment by garfieldbanks** [comment]
Here's my log of the commands to build:
![image](https://user-images.githubusercontent.com/12904270/91266834-4a0bfc00-e72f-11ea-8493-391a4f7c94ac.png)

**Comment by navendu-pottekkat** [comment]
> I tried to install it from source but it has errors:
> ![image](https://user-images.githubusercontent.com/12904270/91266625-e2ee4780-e72e-11ea-9359-68b23aff239d.png)
> 
> It also fails a lot more than the 1.0 version did when I test it on bing.

These errors are from TensorFlow and since the extension is in development mode, it is shown. It should not be a problem. But the model performance should not be affected by this.

@YegorZaremba What do you think?

**Comment by navendu-pottekkat** [comment]
> Here's my log of the commands to build:
> ![image](https://user-images.githubusercontent.com/12904270/91266834-4a0bfc00-e72f-11ea-8493-391a4f7c94ac.png)

This looks okay

**Comment by garfieldbanks** [comment]
oh wait i forgot to switch to the dev branch lol

**Comment by garfieldbanks** [comment]
gimme a sec and ill try again lol

**Comment by navendu-pottekkat** [comment]
> oh wait i forgot to switch to the dev branch lol

Wait, don't switch it is still under development

**Comment by navendu-pottekkat** [comment]
I tried it with bing apparently the first few images are not being filtered. After I scroll down, it is working. And the images that are not filtered are obvious and should be filtered, this is a bug

**Comment by garfieldbanks** [comment]
ok yeah neither branches work for me, both have errors and fail to block all the images

**Comment by navendu-pottekkat** [comment]
> ok yeah neither branch works for me, both have errors and fail to block all the images

It is working but there is some issue with checking on some images. To be precise, from the 5th image to some 10 more images, the filter is not being applied. This is really strange. But the extension is working perfectly in Google Images.

**Comment by YegorZaremba** [comment]
Hi @garfieldbanks and @TitusRobyK thanks for contributing, we changed our whole codebase by moving to TypeScript, so there are some bugs, I ll check it and fix for today(hope :D). I ll ping you in this issue

> th.bing.com/th/id/OIP.djsoeg1Wo3uOQAY4TI2zKgHaEK?w=194&h=109&c=7&o=5&pid=1.7

OMG, I broke our MutationObserver, will fix asap

I really appreciate people who find bugs, it most valuable for us right now <3

**Comment by YegorZaremba** [comment]
Hi @garfieldbanks @TitusRobyK we have released `v1.2.0` with bug fixes. It's already available in chrome webstore https://chrome.google.com/webstore/detail/nsfw-filter/kmgagnlkckiamnenbpigfaljmanlbbhh

I closed this ticket if bugs left, pls feel free to ping me to reopen

**Comment by garfieldbanks** [comment]
@YegorZaremba 
As far as I can tell the 1.2.0 version on the chrome webstore doesn't seem to work at all.

**Comment by navendu-pottekkat** [comment]
@garfieldbanks I have tested it and it is working! Could you provide more info?

**Comment by YegorZaremba** [comment]
> @YegorZaremba
> As far as I can tell the 1.2.0 version on the chrome webstore doesn't seem to work at all.

You still use chrome 85 and windows 10? I didn't test on this platform, but macOS and chrome doesn't work too, otherwise macOS and firefox works pretty well, dunno yet what's happens

**Comment by garfieldbanks** [comment]
> You still use chrome 85 and windows 10?
Yep.

**Comment by garfieldbanks** [comment]
OK I uninstalled and reinstalled it and it's partially working again. But yeah there are still quite a few bing results unblocked.

**Comment by YegorZaremba** [comment]
> OK I uninstalled and reinstalled it and it's partially working again. But yeah there are still quite a few bing results unblocked.

Great, could you please write search words which you use, you can use https://pastebin.com is some words are nsfw-related

**Comment by garfieldbanks** [comment]
> > OK I uninstalled and reinstalled it and it's partially working again. But yeah there are still quite a few bing results unblocked.
> 
> Great, could you please write search words which you use, you can use https://pastebin.com if some words are nsfw-related

I'm still just using the same steps to reproduce from the original post. Just search bing for 'nsfw', choose images, turn off safe search and scroll down.

**Comment by YegorZaremba** [comment]
@garfieldbanks thanks, I see, yeap there are some hentai/cosplay-related sexy pictures. Our model current has 93% accuracy in porn/nudes-related images
Seems like its ML model issue I'll create a ticket for this and close yours in 72hr

We appreciate your feedback

**Comment by YegorZaremba** [comment]
Splitted this issue to #80 and #73
