### ISSUE TITLE
Setup auto-update for Firefox

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#69]
#### Bug description
Setup auto-update for Firefox https://extensionworkshop.com/documentation/manage/updating-your-extension/

#### Expected result
Firefox auto-updates the extension

#### Actual result
Firefox doesn't auto-update the extension

**Comment by navendu-pottekkat** [comment]
This will not work. This is similar to my comment in #72

**Comment by YegorZaremba** [comment]
we are fine https://discourse.mozilla.org/t/autoupdate-for-created-firefox-extension/36340/4
