### ISSUE TITLE
Setup auto-update for Google Chrome

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#72]
#### Bug description
Setup auto-update for Google Chrome https://developer.chrome.com/apps/autoupdate

#### Expected result
Google Chrome auto updates the extension

#### Actual result
Google Chrome doesn't auto update the extension

**Comment by malathit** [comment]
Hey I would like to work on this issue.

**Comment by YegorZaremba** [comment]
@malathit you are so welcome ❤️ 
ps if get stuck - pls send a PR as is, because no one has googled it yet

**Comment by malathit** [comment]
I just googled a few links and have some idea on how to do this? But I am not sure if I am on the right track. So sent you a slack message. If you could answer, I can proceed.

> The chrome doc in the issue description says we can release the new version using 2 steps (1. URL for the manifest XML file and the URL for .crx file)
> - Can you share the .crx file link where we host the new version?
> - where can we host the update_url that will be mentioned in manifest.json?

**Comment by navendu-pottekkat** [comment]
@malathit I'm not really sure, cause we have not really looked into this. Could you please share the doc you are referring?

**Comment by malathi-thangarajan** [comment]
It's the one in the issue description @navendu-pottekkat 
https://developer.chrome.com/apps/autoupdate

**Comment by navendu-pottekkat** [comment]
@malathit I will just check that and get back to you in just a minute

**Comment by navendu-pottekkat** [comment]
@malathit We are hosting the extension in Google Chrome Webstore but the docs say that -

> If you publish using the Chrome Developer Dashboard, you can ignore this page. You can use the dashboard to release updated versions to users, as well as to the Chrome Web Store.

And [this thread](https://stackoverflow.com/questions/13139627/is-it-possible-to-auto-update-a-chrome-extension-published-on-the-chrome-web-sto) says that you cannot update if you are hosting on the store. You have to use the developer dashboard for that. I think that is because of security concerns.

@YegorZaremba So I guess what we are trying will not work?

@malathit Do you know about it?

**Comment by malathit** [comment]
> @malathit Do you know about it?

I don't know about it @navendu-pottekkat. I was participating in the hacktobertest, and wanted to utilize it to improve my knowledge. I am subscribed to this thread and would be happy to pitch in when we come to a conclusion.

**Comment by navendu-pottekkat** [comment]
Sure, we will check and get back to you.

**Comment by YegorZaremba** [comment]
Hi @navendu-pottekkat Is it the way how you publish new version of nsfw-filter? https://developer.chrome.com/extensions/hosting

if so, we are fine

**Comment by YegorZaremba** [comment]
I guess it similar to with Firefox webstore https://github.com/nsfw-filter/nsfw-filter/issues/69#issuecomment-708244050

**Comment by navendu-pottekkat** [comment]
> Hi @navendu-pottekkat Is it the way how you publish new version of nsfw-filter? https://developer.chrome.com/extensions/hosting
> 
> if so, we are fine

Yes, we are using the dev console, so after each version is released, I update it on the dev console and they will verify it and update on the store.
