### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by Glitchy-Pixel-Gun-3d-Devs** [nsfw-filter/nsfw-filter#75]
I'm always frustrated when I want to report NSFW and if I show the screenshot the NSFW will be blank.

A solution is to Put an option where NSFW Content will have the "NSFW" in bold white.

Thanks.

**Comment by navendu-pottekkat** [comment]
I see, so we replace the image with a watermark of some kind that says the image is NSFW. Is that what you mean? @Glitchy-Pixel-Gun-3d-Devs

**Comment by YegorZaremba** [comment]
Hi, thanks for contributing
Duplication of #2

**Comment by Glitchy-Pixel-Gun-3d-Devs** [comment]
Yep (Sorry for LATE reply)
