### ISSUE TITLE
How to know when the filter is done displaying the SFW images?

### ISSUE THREAD

**Issue by lusseyarmet** [nsfw-filter/nsfw-filter#76]
#### Is your feature request related to a problem? Please describe.

It's not really a feature request and not a bug either, but here's my issue/question.
I'm using this extension in tandem with VBA and Selenium Webdriver in Chrome (using the newly released extension on the store) to make sure I'm not taking into account nsfw images when running my macro. The issue is that it usually takes the filter maybe 0.25 to 0.5 seconds to un-hide the images that are safe for work (i guess to change the visibility attribute), and i'm trying to optimize the macro duration, and I can't find an optimized way to detect when all sfw images have been made visible and not just some of them. 
I have a bit of hacky code rn that checks if the number of visible items has changed after a second and loops if it has until it hasn't, but is there maybe a variable or something that the code uses that I could check to see if it's done re-displaying the safe images? 

If there isn't, that's fine, I just wanted to make sure because if there is that'd be great.

(To the people that helped me for my last issue, sorry for not replying last time, I don't check github very often.)

Thanks! :)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Can help you with this.

**Comment by YegorZaremba** [comment]
Hi @lusseyarmet . Thanks for sharing for the use case of NSFW-filter. We don't have this variable, but you can add `image._isNSFW = true` here https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L37 and here https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L58
And `npm run build` for your Chrome and Selenium (dunno is it possible do load custom extensions)

Probably, we should add this `var` in code for informational reasons like your case

**Comment by YegorZaremba** [comment]
We have very simple logic https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L60 and https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L39 right now

But it'll be better to add `element._isNSFW = true | false` variable for informational reasons, you can build and load(not sure) in your chrome & selenium extension with these changes

ps its simple but chrome webstore moderates ~5 days any release

**Comment by lusseyarmet** [comment]
But is there a way to know when the script is done? Here's an example, say I load a page with 20 images that include 5 nsfw images. 
The images are hidden as soon as I load the page, and then if I wait 500 milliseconds 15 images will be displayed.
However, if I only wait say 200 milliseconds, not all safe images will be displayed, maybe 10 will be displayed for example. And then after 100-300 milliseconds the other ones will have been unhidden as well. 
Is there a way to know when the script has done checking all images and then shown ALL safe images? 
Because the time it takes varies depending on the page, so a dynamic way to know this would be nice and would help optimize my macro.

Thanks for the quick reply though! ^^

**Comment by YegorZaremba** [comment]
We use `MutationObserver` to watch mutations of DOM elements https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/DOMWatcher/DOMWatcher.ts#L84

Not sure that there are any reasons for implementation, but if so our implementation would be like "wait 5 seconds, if there aren't new mutations - filtering is done(scrolling? lazy loading?)"

you are welcome)
