### ISSUE TITLE
Ability to change models somewhat easily?

### ISSUE THREAD

**Issue by lusseyarmet** [nsfw-filter/nsfw-filter#77]
#### Is your feature request related to a problem? Please describe.

Could someone explain how I (or anyone else) could change the model the extension uses? 
I have a pretty decent computer and I've found I get way better results with the "HUGE" Inception V3 Model than with the normal one when I use https://nsfwjs.com , especially when I try to filter smaller pictures. So I'd expect to also get better results if I could get the extension to use it as well. 

Is there a somewhat simple way to do this? I'd like to try, anyway.
(This sort of information could also be put on the front page / Readme for the extension by the way, i'm sure other people could have this question in the future.)
Thanks!

**Comment by navendu-pottekkat** [comment]
You can use any model @lusseyarmet You just have to change the files in the `models` folder under `dist/models` 

The model has to be of tfjs format. You can convert TensorFlow model to this format.

The MobileNet version is smaller and is under the recommended size by TensorFlow, you can change it suit your needs.

**Comment by YegorZaremba** [comment]
Hope we answered your question, if not, please ping me to reopen
