### ISSUE TITLE
Create design for popup page

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#79]
It will be great to have a design in Figma.com so we can quickly edit future changes

What should be in the popup?
1. [Logo](https://github.com/nsfw-filter/nsfw-filter/tree/master/dist/images), `NSFW Filter` title
1. Bar to adjust the strictness of filtering #58
1. Dropdown menu to select type how to filter images: a watermark(cover NSFW image with [logo](https://github.com/nsfw-filter/nsfw-filter/tree/master/dist/images)), hidden or blur #2 
1. Counter for total filtered images and videos #78 
1. Some text and links to our website [NSFW-filter.com](https://nsfw-filter.com/) or [GitHub](https://github.com/nsfw-filter/nsfw-filter)

Some examples

![image](https://user-images.githubusercontent.com/31797554/92141775-933d0980-ee1b-11ea-894a-b9f360f6b6b3.png)
![image](https://user-images.githubusercontent.com/31797554/92140479-d5fde200-ee19-11ea-932a-c093c5aefa1f.png)
![image](https://user-images.githubusercontent.com/31797554/92140919-6b00db00-ee1a-11ea-80ee-1d36bb3ab636.png)
![image](https://user-images.githubusercontent.com/31797554/92140976-7bb15100-ee1a-11ea-889e-49ac39c5297e.png)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Yeah, we could do something like this. Let us see if we get any contributors to help us out with this.

**Comment by navendu-pottekkat** [comment]
@YegorZaremba I will design the popup, could you share your ideas on what should be present in the pop up?

**Comment by YegorZaremba** [comment]
@navendu-pottekkat sth like this
![Untitled-2020-09-27-1501](https://user-images.githubusercontent.com/31797554/94364643-a4ec9680-00d3-11eb-94ba-43b2701ed963.png)

https://excalidraw.com/#json=5100098803466240,hjLIIOBD3m7p_vovgAljEQ

**Comment by navendu-pottekkat** [comment]
Thanks, I will make one this week and make PR

**Comment by YegorZaremba** [comment]
Great, pls don't worry about js logic and building process with webpack, just html layout with styles and fonts (preferably no vendor dependencies)

**Comment by navendu-pottekkat** [comment]
Yes, I will leave the js implementation to you. Only popup.html for me

**Comment by YegorZaremba** [comment]
Done https://github.com/nsfw-filter/nsfw-filter/pull/110
