### ISSUE TITLE
Update NSFW model to increase accuracy

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#80]
Right now we use [nsfw-model](https://github.com/nsfw-filter/nsfw_model) v1.0.0
But there are [two more versions](https://github.com/nsfw-filter/nsfw_model/releases), needs to update to the last one and test its performance

**Comment by navendu-pottekkat** [comment]
I checked the [latest release](https://github.com/GantMan/nsfw_model/releases/tag/1.2.0) of the NSFW model and tried replacing our current model in the `dist/models` file with this model but it does not seem to work. Do we need any changes in the rest of the code? 

As far as I know, we point to the `models` folder and load the model using the function. @YegorZaremba You can check by replacing the content of the `models` folder with this: https://github.com/GantMan/nsfw_model/releases/download/1.2.0/mobilenet_v2_140_224.1.zip

with the ones in the `web_model` folder.

**Comment by YegorZaremba** [comment]
Hi @navendu-pottekkat get it, thanks for testing, I'll check later

**Comment by navendu-pottekkat** [comment]
@YegorZaremba If it is not an error or due to not making changes in the code, let me know and I will test the model out. But replacing the files is the only thing necessary as far as I know.
