### ISSUE TITLE
Some things are getting broken on Reddit and Twitter

### ISSUE THREAD

**Issue by hsusanoo** [nsfw-filter/nsfw-filter#81]
#### All **Reddit** posts' content are hidden, except for images, videos and awards icons :
![image](https://user-images.githubusercontent.com/35850056/92303956-afeb5580-ef71-11ea-8c7b-1d51ab2a0b0b.png)

#### Twitter videos' controls are hidden
What's expected:
![image](https://user-images.githubusercontent.com/35850056/92304200-b7abf980-ef73-11ea-8a13-7bd2651f5323.png)
What I get:
![image](https://user-images.githubusercontent.com/35850056/92304165-70be0400-ef73-11ea-8021-7793e72eadfe.png)

* Version used: 1.2.0
* Browser Name and version: Firefox Developer Edition 81.0b6

**Comment by YegorZaremba** [comment]
Hi @hsusanoo thanks a lot for contributing, I faced with disappearing `controls` on Twitter too
Reddit behaviour probably related: #73 

As for Twitter, needs to fix `VideoFilter`

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @hsusanoo for bug

**Comment by YegorZaremba** [comment]
Hi. we have released v1.3.0. It's already available in Chrome and Firefox webstores
Feel free to re-open
