### ISSUE TITLE
Something wrong with the notion.so

### ISSUE THREAD

**Issue by lizhendong128** [nsfw-filter/nsfw-filter#82]
#### Bug description

When I open the www.notion.so, many important elements in the pages are not loaded.

#### Expected result

<img width="943" alt="Snipaste_2020-09-05_21-18-09" src="https://user-images.githubusercontent.com/24618122/92305833-5d378b00-efbd-11ea-8128-13a4fa1312e7.png">

#### Actual result

<img width="938" alt="Snipaste_2020-09-05_21-19-06" src="https://user-images.githubusercontent.com/24618122/92305848-80623a80-efbd-11ea-9d75-3e93bb0eb2b1.png">

#### Your Environment

* Version used:1.2.0
* Browser Name and version: Edge 85.0.564.44
* Operating System and version: Windows 10 home Edition 1909
* Link to your project: None

**Comment by YegorZaremba** [comment]
Hi @lizhendong128 thanks for contributing, really appreciate it

Scope: https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L26
Probably related: #81

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @lizhendong128 for bug

**Comment by YegorZaremba** [comment]
Hi. we have released v1.3.0. It's already available in Chrome and Firefox webstores
Feel free to re-open
