### ISSUE TITLE
The extension mistakenly broke Notion and Reddit

### ISSUE THREAD

**Issue by miaokun-normal** [nsfw-filter/nsfw-filter#86]
#### Bug description
The extension makes Notion inaccessible and Reddit couldn't load properly

#### Actual result
Notion web app went blank, and some parts of the Reddit website are broken

#### Your Environment

* Version used: 1.2.0
* Browser Name and version: Firefox 81.0b8 (64-bit)
* Operating System and version: Windows 10 (64-bit) OS Buil 19041.508

**Comment by navendu-pottekkat** [comment]
Thanks for sharing @miaokun-normal . We have a similar bug and we are looking into how we can fix this. 

Probably similar issues: #81 #82 

If you can help us fix it please do so. @all-contributors please add @miaokun-normal for bug

**Comment by YegorZaremba** [comment]
Hi. we have released v1.3.0. It's already available in Chrome and Firefox webstores
Feel free to re-open
