### ISSUE TITLE
Qst

### ISSUE THREAD

**Issue by yezz123** [nsfw-filter/nsfw-filter#91]
Hey! 
I wanna ask if this extension can work  in incognito window and in Porn website?

**Comment by YegorZaremba** [comment]
Hi @yezz123 after installation, you will be prompted about private/incognito mode, or go to extension settings and mark over there
As for porn websites - sure, it works for any porn website with images (videos under development)

<img width="412" alt="Screen Shot 2020-09-22 at 4 21 58 PM" src="https://user-images.githubusercontent.com/31797554/93887726-be669a80-fcef-11ea-8fce-2639f3eeefef.png">
