### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by navendu-pottekkat** [nsfw-filter/nsfw-filter#92]
Here are some changes I would suggest to the README. @YegorZaremba please check all that you think should be made and connect with me on the Slack Channel.

- [ ] **Add "Featured in Product Hunt" image**-  I think this is necessary because people will easily notice this and being featured makes this project more reputable.

- [x] **Change the "NSFW Filter" text image**- I will make a design with our original fonts. Also aligning this to the left would look good.

- [x] **Make the shields badges flat-square**

- [ ] **Improve the opening paragraph**- The first lines should be made better.

- [ ] **Remove bold where it is not necessary**

- [ ] **Download image quality improvement**- I will make the GIFs in a better resolution.

- [ ] **Show the license at the bottom of the README**- I think this is a good practice.

- [ ] **Improve the activity diagram**- The activity diagram is not clear.

I will make the changes as necessary and make the PR.

**Comment by YegorZaremba** [comment]
Hi @navendu-pottekkat 

> **Show the license at the bottom of the README**

we already have this data on the right side

<img width="381" alt="Screen Shot 2020-09-22 at 6 05 10 PM" src="https://user-images.githubusercontent.com/31797554/93900528-2a4fff80-fcfe-11ea-8485-3adc0f8719fd.png">

and according [nsfwjs](https://github.com/infinitered/nsfwjs#table-of-contents), they are not use Licence info on the bottom. Also I think that this info isn't important for our case

---
> **Add "Featured in Product Hunt" image**

Their button is so huge. I made a badge for ProductHunt, but yeah, not great, dunno what to do
<img width="261" alt="Screen Shot 2020-09-22 at 6 08 45 PM" src="https://user-images.githubusercontent.com/31797554/93900955-ab0efb80-fcfe-11ea-95e9-81c0a497d8d3.png">

I suggest to add a section(between **Usage** and **Installation**) where we'll add links for all this stuff, like Hacker Noon, Towards Data Science and etc
---

The rest of points are excellent, I appreciate your efforts 🚀

**Comment by navendu-pottekkat** [comment]
>  Improve the activity diagram- The activity diagram is not clear.

One more stuff I forgot to mention was that the activity diagram is not clear
Do you know of some tool that will allow us to host this diagram someplace else? Because it is not clear in the README

**Comment by YegorZaremba** [comment]
@navendu-pottekkat Can we close it?

**Comment by navendu-pottekkat** [comment]
@YegorZaremba yes we can close
