### ISSUE TITLE
Almost all images disappearing

### ISSUE THREAD

**Issue by kitsune7** [nsfw-filter/nsfw-filter#93]
#### Bug description

When this extension is installed in my Chrome browser, almost every image that's not in a header or footer element is getting hidden. It took me a bit of time to figure out that the extension was causing an issue. The issue disappeared as soon as I removed the extension.

#### Expected result

I expect that there are few false positives on images that are hidden.

#### Actual result

There is a large number of false positives preventing normal usage on most websites.

#### Steps to reproduce

For one example:

1. Install the extension
2. Go to [https://databased.com/team](https://databased.com/team)
3. The main team image is hidden
#### Context

There have also been a lot of false positives on other websites like
* Most images on [picrew.me](https://picrew.me/)
* [partitionwizard.com](https://www.partitionwizard.com/partitionmagic/images-not-showing-in-google-chrome-024.html)
* [Gmail](https://gmail.com)
* Etc.

#### Your Environment

* Version used: 1.2.0
* Browser Name and version: Google Chrome 85.0.4183.102
* Operating System and version: macOS High Sierra version 10.13.2
* Link to your project: N/A

**Comment by navendu-pottekkat** [comment]
Hi @kitsune7 Thank you for reporting the bug. There seems to be some issues and we will fix it ASAP for the next release.

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @kitsune7 for bug

**Comment by YegorZaremba** [comment]
Hi @kitsune7 thanks for you feedback, related to #58 and #80

**Comment by wingman-jr-addon** [comment]
It's possible that simply updating (#80) might just solve it, but in case it doesn't...
 I have some related experience and I found a couple things that helped improve my model:

- Add the ability for the plugin to feedback images to the training data, then browse many common websites. This really helped to round out the small icon category.
- Skip filtering images that are below a certain dimension. It's hard for a 2x2 pixel image to be suggestive. :)

Unfortunately the first one might require finetuning the NSFW.js model. I'm not sure what's in their drawing category but maybe rounding that out with more icons might similarly help, too.

**Comment by navendu-pottekkat** [comment]
I also found some images like posters and logos getting blocked and I think these were not part of the training images. @YegorZaremba what do you think?

We could maybe re-train the nsfw model to include all these from scratch. 

@wingman-jr-addon Do you have a better model? We can maybe use it instead

**Comment by wingman-jr-addon** [comment]
Well I'm kind of a [friendly competitor](https://github.com/wingman-jr-addon/wingman_jr) but mostly I'd just like a good plugin for the world to use. I've been meaning to release the model separately, but feel free to use the TF.js model (CC0 license) in that repo at [this location](https://github.com/wingman-jr-addon/wingman_jr/tree/master/sqrxr_62_graphopt) if you'd like. The key prediction code starts [here](https://github.com/wingman-jr-addon/wingman_jr/blob/master/background.js#L213); the output of the model is a threshold that maps against a ROC curve to provide false positive vs. true positive rate tradeoff. A good starting point for a threshold would be the one found [here](https://github.com/wingman-jr-addon/wingman_jr/blob/master/background.js#L145).

**Comment by navendu-pottekkat** [comment]
@wingman-jr-addon thank you for sharing that. We will check and see how we can add that. You are always welcome to join this project and collaborate with us. You can [join the slack channel](https://join.slack.com/t/nsfwfilter/shared_invite/zt-gt1lgdiv-K2VR~UVUxwaTPWCLSmDiug) to reach out to us directly.

**Comment by navendu-pottekkat** [comment]
@all-contributors please add @wingman-jr-addon for ideas

**Comment by YegorZaremba** [comment]
Hi @wingman-jr-addon , checked your repo, amazing work man
Could I ping you when we done with #90 to test v1.3.0 release (approx October 20), cause you have already had exp with familiar project so you can give great feedback

> Add the ability for the plugin to feedback images to the training data, then browse many common websites. This really helped to round out the small icon category

Great idea, but its means that we need full pipeline of model training, not in the recent future I guess. But eventually we'll be here

> Skip filtering images that are below a certain dimension. It's hard for a 2x2 pixel image to be suggestive. :)

Yeah, we already skip them https://github.com/nsfw-filter/nsfw-filter/blob/master/src/content/Filter/ImageFilter.ts#L16

**About blocking**

As you see https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/Model.ts#L111 we have so aggressive nsfw predictions right now, it fixes by #58

**Comment by navendu-pottekkat** [comment]
We can create a pipeline for making the model in the future. I will see how we can build that.

**Comment by YegorZaremba** [comment]
@navendu-pottekkat Yeah, you can, but it's so huge task for now
I see it like users send images url via extension, after that we clean data and every month(?) we retrain model

https://github.com/nsfw-filter/nsfwjs#more
> The model was trained in Keras **over several days** and **60+ Gigs** of data. Be sure to check out the model code which was trained on data provided by Alexander Kim's nsfw_data_scraper.

**Comment by navendu-pottekkat** [comment]
Maybe this could be v2.0.

I will check it out.

**Comment by YegorZaremba** [comment]
FYI, Google Drive allow to store GBs of the NSFW data https://support.google.com/photos/thread/17111236?hl=en

**Comment by YegorZaremba** [comment]
Hi. we have released v1.3.0. It's already available in Chrome and Firefox webstores
Feel free to re-open
